services:
  - type: web
    name: awintour
    env: node
    plan: free
    buildCommand: npm install && npm run build:js
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.18.0
